stages:
  - build

build:
  image: node:18
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm ci --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - dist/
