image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - main

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo 'Deploying to GitLab Pages'
  artifacts:
    paths:
      - dist
  only:
    - main
  when: always
